name: nv
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  ############### App Dependency ###############
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  path_provider: ^2.1.5
  responsive_sizer: ^3.3.1
  get: ^4.6.6
  icons_plus :
  get_storage: ^2.1.1
  flutter_animate: ^4.5.2
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.1
  lottie: ^3.1.1
  animated_bottom_navigation_bar: ^1.3.3
  connectivity_plus: ^6.1.1
  double_back_to_close_app: ^2.1.0
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  photo_view: ^0.15.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  flutter_staggered_animations: ^1.1.1
  iconsax: ^0.0.8
  share_plus: ^10.1.3
  blur: ^4.0.0
  table_calendar: ^3.1.3
  carousel_slider: ^5.0.0
  csv: ^6.0.0
  flutter_excel: ^1.0.1
  file_picker: ^8.3.3
  logger: ^2.5.0
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  ###############  App Assets  ###############
  assets:
    - assets/Images/Config_Images/
    - assets/Images/Home_Images/
    - assets/Animations/
    - assets/Icons/

  ############### App Fonts ###############
  fonts:
    - family: poppins
      fonts:
        - asset: assets/Fonts/Poppins-Regular.ttf
    - family: montserrat
      fonts:
        - asset: assets/Fonts/Montserrat-Regular.ttf

