// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpbi3sJMUqIL9GdtUf1fXdKFVniaMbOHA',
    appId: '1:784367837816:web:6e6b055f380fff4e97038d',
    messagingSenderId: '784367837816',
    projectId: 'garage-app-0',
    authDomain: 'garage-app-0.firebaseapp.com',
    storageBucket: 'garage-app-0.firebasestorage.app',
    measurementId: 'G-0MV2RPLP2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsE587juOo1ZtLMEbxKjcDX7Tduf3he3c',
    appId: '1:784367837816:android:b319dbf140faa8c397038d',
    messagingSenderId: '784367837816',
    projectId: 'garage-app-0',
    storageBucket: 'garage-app-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrCxe2pA-ireuA_ULaBztupUmwCHa1OM',
    appId: '1:784367837816:ios:9005d52f87d043b997038d',
    messagingSenderId: '784367837816',
    projectId: 'garage-app-0',
    storageBucket: 'garage-app-0.firebasestorage.app',
    iosBundleId: 'com.nv.nv',
  );
}
